runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /set_webhook
  login: admin
  script: main.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: PIL
  version: latest
